### ISSUE TITLE
Instant Fall Damage Death When Sent To Nether

### ISSUE THREAD

**Issue by Banaando** [The-Fireplace-Minecraft-Mods/Unforgiving-Void#1]
(Now I know that this bug has already been talked about before, but nobody has ever posted it here where it should go so I'll be the one to do it.) When you get teleported into the Nether, you instantly die of fall damage unless you get teleported into lava.

You reproduce this by falling into the void. Not much to it.

Video:
https://user-images.githubusercontent.com/67934979/107902665-1c04b900-6f15-11eb-8bf9-38afe9ffd101.mp4

Version Info:
 - Minecraft: 1.16.5
 - Mod Version: 2.0.0
 - Fabric API: 0.11.0
 - (Also there were no other mods installed)

**Comment by The-Fireplace** [comment]
Thanks for reporting, I'll take a look when I get the chance.

**Comment by MSandro** [comment]
hope this could be fixed soon. would be very nice.

**Comment by The-Fireplace** [comment]
Fixed in Unforgiving Void 3.0.0, which is currently on Patreon and will be out on CurseForge and Modrinth in a week.
