### ISSUE TITLE
Publish version 3.1.4 on Modrinth

### ISSUE THREAD

**Issue by solonovamax** [The-Fireplace-Minecraft-Mods/Unforgiving-Void#15]
**Describe the bug**
Version 3.1.4 is not published on modrinth.

**To Reproduce**
1. Go to the modrinth page
2. Click on versions
3. Version 3.1.4 is not there.

**Comment by The-Fireplace** [comment]
Version 3.1.4 is not released anywhere. It's still buggy, and I haven't taken the time to fix it yet.

**Comment by solonovamax** [comment]
It's buggy? How so?

**Comment by The-Fireplace** [comment]
I just did more testing, and there seems to be some weirdness occasionally with spawning in the Nether. Fall from sky spawned me in the bottom of a lava lake, well below the roof of the Nether. The first time I tested, one of the settings managed to spawn me on the roof of the Nether (I don't recall which). In any case, I think I'll go ahead and release it as a beta so you can get the fixes it has to offer.

**Comment by The-Fireplace** [comment]
Released it

**Comment by solonovamax** [comment]
@The-Fireplace

hmm, unsure why it's spawning you inside of a lava lake.

I'd have to check how `Box#isSpaceEmpty` works, as this is the code which determines whether or not it's a valid location: https://github.com/The-Fireplace-Minecraft-Mods/Unforgiving-Void/blob/1.18.2/src/main/java/dev/the_fireplace/unforgivingvoid/usecase/SpawnPositionLocator.java#L146-L150
