### ISSUE TITLE
Keeps teleporting to random places in the nether

### ISSUE THREAD

**Issue by kaphion** [The-Fireplace-Minecraft-Mods/Unforgiving-Void#3]
Whenever I fall into the void in the end and get teleported to the nether it keeps on teleporting me to random places in the nether between -300 x/z and +300 x/z.

I can reproduce this by falling into the void

Video: https://youtu.be/UA1Xx7iUFBg

 - Minecraft: 1.16.5
 - Mod Version: 2.0.0
 - Fabric API: Fabric API 0.31.0

Note: This is on a server not singleplayer

![image](https://user-images.githubusercontent.com/35414331/112725435-86e3df80-8f18-11eb-98d6-c90c5fe4704b.png)
Modlist (I removed the mod here since it was causing problems.)

**Comment by The-Fireplace** [comment]
Fixed in Unforgiving Void 3.0.0, which is currently on Patreon and will be out on CurseForge and Modrinth in a week.

**Comment by Sirkilium** [comment]
This issue appears be happening again on 3.1.1+1.18

**Comment by The-Fireplace** [comment]
Should be fixed in 3.1.3. Comment if you have any more issues.
