### ISSUE TITLE
Unforgiving void not compatible with Interdimensional?

### ISSUE THREAD

**Issue by imasuu** [The-Fireplace-Minecraft-Mods/Unforgiving-Void#5]
**Describe the bug**
in singleplayer, configuring dimensions will not show the dimensions made by interdimensional and doing manual config files does not change it.

**To Reproduce**
1. install:
     interdimensional: https://www.curseforge.com/minecraft/mc-mods/interdimensional
     Unforgiving void
     fantasy :https://github.com/nucleoidmc/fantasy
     polymer: https://github.com/Patbox/polymer/releases/tag/0.2.0-beta.18%2B1.18.1
    
2. go to mod config
3. see that it cannot find your custom dimension made by interdimensional

**Screenshot**
![2022-01-23_15 58 06](https://user-images.githubusercontent.com/71387786/150687013-15a0d2f5-ff94-4850-b40f-daf02f2641ec.png)

**Versions**
 - Minecraft: 1.18.1
 - unforgiving void Version: 3.1.1
 - interdimensional Version: 1.1.1
 - Fabric API: 0.46.1

**Comment by The-Fireplace** [comment]
Did you go to the Unforgiving Void config from the main menu, or open it when you're connected to a world?

Dimensions are tricky now, you need to open the config when you're in-game to see more than the default ones.
