### ISSUE TITLE
Server crash on player join

### ISSUE THREAD

**Issue by MaranRoseGIT** [The-Fireplace-Minecraft-Mods/Unforgiving-Void#6]
**Describe the bug**
After the setup phase of the server, nothing appears to be wrong; as soon as a player joins though, the server soft-crashes, providing an error similar to what is logged below

**To Reproduce**
1. Have latest version of mod installed both sides (client and server)
2. Start server up, let it run before joining
3. Join the game
4. Error appears and game crashes

**Logs/Screenshots/Videos**
(https://gist.github.com/RoseTheFoxGit/2d1c82abfe8f3935ff9a34d327bf3b04)

**Versions**
 - Minecraft: 1.18.2
 - Mod Version: 3.1.1
 - Fabric API: 0.48.0+1.18.2

**Comment by t0mtee** [comment]
Same issue here

**Comment by The-Fireplace** [comment]
Will be fixed in version 3.1.2, I'm getting it ready to release in a few minutes.
